version: "3"
services:
  api:
    container_name: pandemino_api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/api:/app
    command: "npm start"

  postgres:
    container_name: pandemino_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pandemino"
