version: "3"
services:
  api:
    container_name: pandemino_api
    image: node

    ports:
      - "3000:3000"
    volumes:
      - ./packages/api:/app
    command: "npm run dev"

  postgres:
    container_name: pandemino_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pandemino"
