version: "3"
services:
  api:
    container_name: pandemino_api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/api:/app
    command: "npm start"
    env_file:
      - ./packages/api/.env
    environment:
    - NODE_ENV=production
    - DB_HOST=pandemino_postgres
    - LOG_PATH=/var/log/
  streams:
    container_name: pandemino_streams
    build:
      context: ./packages/streams/.
      dockerfile: dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./packages/streams:/app
    command: "npm start"
    env_file:
      - ./packages/streams/.env
    environment:
    - NODE_ENV=production
    - DB_HOST=pandemino_postgres
    - LOG_PATH=/var/log/
  postgres:
    container_name: pandemino_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pandemino"
