version: "3"
services:
  api:
    container_name: pandemino_api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/api:/app
    command: "npm start"
    environment:
      PORT: 5000
      LOG_PATH: "/var/log/"
      NODE_ENV: "development"
      DB_HOST: "pandemino_postgres"
      DB_USERNAME: "test"
      DB_PASSWORD: "test"
      DB_DATABASE: "pandemino"
      DB_PORT: 5432
  postgres:
    container_name: pandemino_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pandemino"
