version: "3"
services:
  api:
    container_name: pandemino_api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/api:/app
    command: "npm start"
    environment:
      TYPEORM_CONNECTION: "postgres"
      TYPEORM_HOST: "pandemino_postgres"
      TYPEORM_USERNAME: "test"
      TYPEORM_PASSWORD: "test"
      TYPEORM_DATABASE: "pandemino"
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: "src/db/entity/**/*.ts"
  postgres:
    container_name: pandemino_postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pandemino"
