version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - dev.env

  django_api:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      - dev.env
