version: "3.1"

services:
  db:
    image: postgres:12.3
    restart: always
    env_file:
      - dev.env

    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  django_api:
    build: .
    restart: always
    expose:
      - "8080"
    ports:
      - 8080:8080
    env_file:
      - dev.env
