version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - dev.env
    expose:
      - "5432"
    ports:
      - 5432:5432

  django_api:
    build: .
    restart: always
    expose:
      - "80"
      - "8080"
    ports:
      - 8080:8080
    env_file:
      - dev.env
