version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - run: cd packages/api && npm install
  test:
    docker:
      - image: node:14
    steps:
      - run: cd packages/api && npm install

workflows:
  test-api:
    jobs:
      - build
      - test

