version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-api-and-test:
    executor:
      name: node/default
      tag: '13.14'
    working_directory: ~/packages/api
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
  test-api:
    jobs:
      - build-api-and-test

