version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: cd packages/api && npm install && npm run build
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: cd packages/api && npm install && npm run test

workflows:
  version: 2
  test-api:
    jobs:
      - test

